name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Шаг 1: Получить код из репозитория
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Шаг 2: Настроить Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
    
    # Шаг 3: Установить зависимости
    - name: Install dependencies
      run: npm install
    
    # Шаг 4: Собрать проект
    - name: Build project
      run: npm run build
    
    # Шаг 5: Создать файл .nojekyll
    - name: Create .nojekyll file
      run: touch build/.nojekyll
    
    # Шаг 6: Деплой на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
